### ISSUE TITLE
emphasis on vision

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-inclusion#26] opened 2016-12-14 01:03 UTC
in http://w3c.github.io/wai-inclusion/#accessible-usable under **Requirements that are technical** 

1. we put screen reader and screen magnifiers (blindness and low vision) ahead of voice recognition (non-mouse user) which may reinforce the 'screen reader' bias we see in web accessibility
2. we say "they ensure that websites work well with assistive technologies" - suggest we add "and adaptive strategies" to pick up other non-mouse use, change of text size, etc and link 'adaptive strategies' to https://www.w3.org/WAI/users/browsing

All at editors discretion :)

**Comment by nitedog** [comment] 2016-12-14 13:04
1. I'm not opposed to flipping the order but wonder about starting with the most compelling argument first - that is, the situation that is most common and most obvious. I'd like EOWG input on this.
2. The problem is that "adaptive strategies" often fall between pure technical/interoperability and interaction - like text size is not really a coding issue. I wonder if this will add too much complexity for relatively little value?

**Comment by bakkenb** [comment] 2016-12-14 21:49
I am neutral on these two points. Editors discretion on both. I would just make your best judgement on these @nitedog and go with them.

**Comment by shawna-slh** [comment] 2016-12-14 22:23
While I appreciate the thought, in this case, I think it's best to leave it as is for the reasons Shadi states.

**Comment by nitedog** [comment] 2016-12-15 08:23
@AndrewArch - is this sufficient feedback to close this issue or do you want more discussion on it?

**Comment by yatil** [comment] 2017-10-18 12:44
I leave this to the Editor.

**Comment by shawna-slh** [comment] 2018-02-22 18:49
Closing. @AndrewArch or others can re-open if you want.

**Closed as completed by shawna-slh** 2018-02-22 18:49 UTC
